# Generated by Django 6.0.3 on 2026-04-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beverages', '0002_beverage_category_and_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beverage',
            options={'ordering': ['category', 'name', 'size'], 'verbose_name': 'Beverage', 'verbose_name_plural': 'Beverages'},
        ),
        migrations.RemoveField(
            model_name='beverage',
            name='volume_ml',
        ),
        migrations.AlterField(
            model_name='beverage',
            name='name',
            field=models.CharField(help_text='e.g. Coca-Cola, Sprite, Fanta Orange', max_length=100),
        ),
        migrations.AlterField(
            model_name='beveragestock',
            name='quantity',
            field=models.IntegerField(help_text='Number of units (bottles/cans)'),
        ),
    ]
