# Generated by Django 6.0.3 on 2026-03-30 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_first_name_remove_client_gender_and_more'),
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, default='noemail@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, default='noemail@example.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, default='noemail@example.com', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.salon'),
        ),
    ]
