# Generated by Django 6.0.3 on 2026-04-03 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_birthday_preferred_worker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
    ]
