# Generated by Django 6.0.3 on 2026-03-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('retail', 'Retail'), ('consumable', 'Consumable')], default='retail', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('unit', 'Unit'), ('gram', 'Gram')], default='unit', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='source',
            field=models.CharField(choices=[('sale', 'Sale'), ('service', 'Service'), ('purchase', 'Purchase'), ('adjustment', 'Adjustment')], default='unit', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
