# Generated by Django 6.0.3 on 2026-03-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_product_type_product_unit_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('retail', 'Retail'), ('consumable', 'Consumable')], default='retail', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The price the customer pays', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('unit', 'Unit'), ('gram', 'Gram')], default='unit', max_length=20),
        ),
    ]
