# Generated by Django 6.0.3 on 2026-03-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_cost_price_alter_product_product_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('unit', 'Unit'), ('gram', 'Gram'), ('ml', 'Milliliters')], default='unit', max_length=20),
        ),
    ]
