# Generated by Django 6.0.3 on 2026-07-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_humanhair_hairtexture_hairstockmovement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hairtexture',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterField(
            model_name='hairstockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out')], max_length=10),
        ),
        migrations.AlterField(
            model_name='hairstockmovement',
            name='reference',
            field=models.CharField(blank=True, help_text='e.g. Sale #12', max_length=255),
        ),
        migrations.AlterField(
            model_name='hairstockmovement',
            name='source',
            field=models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('adjustment', 'Adjustment'), ('returned', 'Returned')], max_length=20),
        ),
        migrations.AlterField(
            model_name='humanhair',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='humanhair',
            name='length_inch',
            field=models.PositiveIntegerField(help_text='Length in inches'),
        ),
        migrations.AlterField(
            model_name='humanhair',
            name='low_stock_alert',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='humanhair',
            name='name',
            field=models.CharField(blank=True, help_text='Auto-filled if left blank', max_length=255),
        ),
        migrations.AlterField(
            model_name='humanhair',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
