# Generated by Django 6.0.3 on 2026-03-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
