# Generated by Django 6.0.3 on 2026-04-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon_services', '0004_alter_service_category_alter_service_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name_plural': 'Service Categories'},
        ),
        migrations.RemoveField(
            model_name='serviceproduct',
            name='quantity',
        ),
        migrations.AddField(
            model_name='serviceproduct',
            name='quantity_used',
            field=models.FloatField(default=0, help_text='Amount used per service (ml or units)'),
            preserve_default=False,
        ),
    ]
