# Generated by Django 6.0.3 on 2026-03-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_salon_sale_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='item_type',
            field=models.CharField(choices=[('service', 'Service'), ('product', 'Product')], max_length=50),
        ),
    ]
