# Generated by Django 6.0.3 on 2026-03-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_saleitem_name_alter_saleitem_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='item_type',
            field=models.CharField(choices=[('service', 'Service'), ('product_sale', 'Product Sale'), ('product_use', 'Product Used')], max_length=20),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.FloatField(default=1),
        ),
    ]
