# Generated by Django 6.0.3 on 2026-04-03 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_add_worker_payment_method_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at']},
        ),
    ]
