# Generated by Django 6.0.3 on 2026-07-14 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beverages', '0003_alter_beverage_options_remove_beverage_volume_ml_and_more'),
        ('inventory', '0006_alter_hairtexture_options_and_more'),
        ('sales', '0006_alter_sale_options'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='beverage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beverages.beverage'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='human_hair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.humanhair'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='item_type',
            field=models.CharField(choices=[('service', 'Service'), ('product_sale', 'Product Sale'), ('product_use', 'Product Used'), ('beverage', 'Beverage'), ('human_hair', 'Human Hair')], max_length=20),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='staff.staffmember'),
        ),
    ]
